main: mutex
	./mutex

mutex: mutex.cpp
	g++ mutex.cpp -o mutex -pthread


spinlock: spinlock.cpp
	g++ spinlock.cpp -o spinlock -pthread


semaphore: semaphore.cpp
	g++ semaphore.cpp -o semaphore -pthread